version: "3.9"
services:
  rtmp:
    build: ./rtmp
    ports:
      - "1935:1935"
      - "7080:8080"
    container_name: rtmp_server
    volumes:
      - ./hls:/tmp/hls
      - ./dash:/tmp/dash

  auth:
    build: ./auth
    container_name: auth_server