version: "3.9"
services:
  rtmp:
    build: ./rtmp
    ports:
      - "1935:1935"
      - "7080:8080"
    container_name: rtmp_server
    volumes:
      - ./hls:/tmp/hls
      - ./dash:/tmp/dash
      - ./hls2:/tmp/hls2
      - ./dash2:/tmp/dash2
      - ./hevc:/tmp/hevc
      - ./www:/tmp/www
  # auth:
  #   build: ./auth
  #   container_name: auth_server